name = "SCORES"
compatibility_date = "2024-01-01"

# Pages Functions kullandığın için 'main' satırına gerek yok.

[[kv_namespaces]]
binding = "SCORES"  # Burası scores.js içindeki 'env.SCORES' ile aynı olmalı
id      = "578f2a8517fa477b8f521a6deb49c16c"

# Preview (local test) için:
# id      = "578f2a8517fa477b8f521a6deb49c16c"
# preview_id = "578f2a8517fa477b8f521a6deb49c16c"
